package com.transfer.flash.core.security.crypto

import android.content.Context
import android.os.Build
import android.security.keystore.KeyGenParameterSpec
import android.security.keystore.KeyInfo
import android.security.keystore.KeyProperties
import android.security.keystore.StrongBoxUnavailableException
import android.util.Log
import java.math.BigInteger
import java.security.KeyFactory
import java.security.KeyPair
import java.security.KeyPairGenerator
import java.security.KeyStore
import java.security.PrivateKey
import java.security.ProviderException
import java.security.Signature
import java.security.cert.X509Certificate
import java.security.spec.ECGenParameterSpec
import java.util.Date
import javax.security.auth.x500.X500Principal

/**
 * AndroidKeyStore-backed [FlashCrypto]: the production identity implementation.
 *
 * Identity key (C2.1):
 * - ECDSA P-256, alias [FlashCrypto.IDENTITY_KEY_ALIAS] = `"flash_identity"`, non-exportable
 *   (`getPrivateKey()` returns an inaccessible handle; the key material never leaves the TEE/StrongBox).
 * - Purposes: SIGN | VERIFY only, digests: SHA-256 only ([KeyProperties.DIGEST_SHA256]).
 * - StrongBox-backed when the device exposes `android.software.keystore.strongbox` on API 28+
 *   (https://developer.android.com/privacy-and-security/keystore#strongbox); silently falls back to
 *   the TEE on [StrongBoxUnavailableException]/[ProviderException].
 * - No user authentication is required for signing; biometric-enrollment invalidation is explicitly
 *   disabled so identity survives fingerprint re-enrollment.
 *
 * ECDH note: this class deliberately does NOT create a keystore AGREEMENT key —
 * `PURPOSE_AGREE_KEY` exists only since API 31 while Flash minSdk is 24. Session keys come from
 * ephemeral software keypairs via [generateEphemeralEcdhKeyPair]/[ecdhSessionKey]; see [FlashCrypto].
 *
 * Certificate (C2.2): the platform generates a self-signed X.509 cert as part of keystore keypair
 * generation from the certificate fields set in the spec (see AOSP
 * AndroidKeyStoreKeyPairGeneratorSpi.generateSelfSignedCertificate:
 * https://android.googlesource.com/platform/frameworks/base/+/master/keystore/java/android/security/keystore/AndroidKeyStoreKeyPairGeneratorSpi.java).
 * [selfSignedCertificate] retrieves it — no BouncyCastle dependency needed (ADR recorded in docs/decisions.md).
 */
public class KeystoreFlashCrypto(private val context: Context) : FlashCrypto {

    private val identityKeyPair: KeyPair by lazy { loadOrGenerateIdentityKey() }

    override val identityPublicKeyEncoded: ByteArray
        get() = identityKeyPair.public.encoded

    override fun sign(data: ByteArray): ByteArray =
        EcP256Ops.sign(identityKeyPair.private, data)

    override fun verify(signature: ByteArray, data: ByteArray, peerPublicKey: ByteArray): Boolean =
        EcP256Ops.verify(peerPublicKey, data, signature)

    override fun generateEphemeralEcdhKeyPair(): FlashEcKeyPair = EcP256Ops.ephemeralKeyPair()

    override fun ecdhSessionKey(
        selfEphemeral: FlashEcKeyPair,
        peerEphemeralPublicKey: ByteArray,
    ): ByteArray =
        EcP256Ops.sessionKeyFromSharedSecret(
            EcP256Ops.agreedSecret(selfEphemeral.privateKey, peerEphemeralPublicKey)
        )

    /**
     * Self-signed X.509 certificate wrapping the identity public key, generated by the
     * platform at key creation time and stored inside the AndroidKeyStore entry.
     * Consumed by the C4 TLS layer (server + client cert) and TOFU fingerprint pinning.
     */
    public fun selfSignedCertificate(): X509Certificate {
        ensureIdentityKeyLoaded()
        val keyStore = openKeyStore()
        return keyStore.getCertificate(FlashCrypto.IDENTITY_KEY_ALIAS) as? X509Certificate
            ?: error("Flash identity certificate missing after key generation")
    }

    private fun ensureIdentityKeyLoaded() {
        identityKeyPair // triggers lazy load-or-generate
    }

    private fun openKeyStore(): KeyStore =
        KeyStore.getInstance(ANDROID_KEYSTORE).apply { load(null) }

    private fun loadOrGenerateIdentityKey(): KeyPair {
        val keyStore = openKeyStore()
        if (keyStore.containsAlias(FlashCrypto.IDENTITY_KEY_ALIAS)) {
            // Verify that the existing key supports NONEwithECDSA required by Conscrypt TLS handshake. R-09: only a DEFINITE
            // verdict regenerates (the key's parameters were read and lack DIGEST_NONE, or the alias holds no private key).
            // A probe that merely failed (a transient KeyStoreException / ProviderException, a daemon restart) is retried and
            // then throws with the key untouched: deleting it would change the device identity and break every pairing.
            val action = IdentityKeyCheck.decide { IdentityKeyCheck.inspect(AndroidIdentityKeyInspector(keyStore)) }
            if (action == IdentityKeyAction.REGENERATE) {
                Log.w(TAG, "Existing identity key lacks DIGEST_NONE (required for TLS Conscrypt handshake) or has no private key; regenerating.")
                keyStore.deleteEntry(FlashCrypto.IDENTITY_KEY_ALIAS)
                generateIdentityKey()
            }
        } else {
            generateIdentityKey()
        }
        val certificate = keyStore.getCertificate(FlashCrypto.IDENTITY_KEY_ALIAS)
            ?: error("Flash identity key missing after generation")
        val privateKey = keyStore.getKey(FlashCrypto.IDENTITY_KEY_ALIAS, null) as PrivateKey
        return KeyPair(certificate.publicKey, privateKey)
    }

    /** The real probe: [KeyInfo] for the parameters, a `NONEwithECDSA` signing operation as the fallback. */
    private class AndroidIdentityKeyInspector(private val keyStore: KeyStore) : IdentityKeyInspector {
        override fun privateKey(): PrivateKey? = keyStore.getKey(FlashCrypto.IDENTITY_KEY_ALIAS, null) as? PrivateKey

        override fun digests(key: PrivateKey): Set<String> {
            val info = KeyFactory.getInstance(key.algorithm, ANDROID_KEYSTORE).getKeySpec(key, KeyInfo::class.java)
            return info.digests.toSet()
        }

        override fun initNoneSigning(key: PrivateKey) {
            Signature.getInstance("NONEwithECDSA").initSign(key)
        }
    }

    private fun generateIdentityKey() {
        val wantStrongBox = strongBoxAvailable()
        try {
            generateKeyPair(strongBox = wantStrongBox)
        } catch (first: Exception) {
            if (wantStrongBox && isStrongboxFallback(first)) {
                generateKeyPair(strongBox = false)
            } else {
                throw first
            }
        }
    }

    private fun generateKeyPair(strongBox: Boolean) {
        val now = System.currentTimeMillis()
        val builder = KeyGenParameterSpec.Builder(
            FlashCrypto.IDENTITY_KEY_ALIAS,
            KeyProperties.PURPOSE_SIGN or KeyProperties.PURPOSE_VERIFY,
        )
            .setAlgorithmParameterSpec(ECGenParameterSpec(FlashCrypto.EC_CURVE))
            .setDigests(
                KeyProperties.DIGEST_NONE,
                KeyProperties.DIGEST_SHA256,
                KeyProperties.DIGEST_SHA384,
                KeyProperties.DIGEST_SHA512,
            )
            .setCertificateSubject(X500_PRINCIPAL)
            .setCertificateSerialNumber(BigInteger.valueOf(now))
            .setCertificateNotBefore(Date(now - CERT_BACKDATE_MS))
            .setCertificateNotAfter(Date(now + CERT_VALIDITY_MS))
            // No user-auth gate on signing; explicit false keeps identity stable across
            // biometric re-enrollment (method itself is API 24+, i.e. >= minSdk).
            .setInvalidatedByBiometricEnrollment(false)
        if (strongBox) {
            builder.setIsStrongBoxBacked(true)
        }
        val generator = KeyPairGenerator.getInstance(
            KeyProperties.KEY_ALGORITHM_EC,
            ANDROID_KEYSTORE,
        )
        generator.initialize(builder.build())
        generator.generateKeyPair()
    }

    /** Literal feature string so API 28 devices qualify without referencing the API 29 constant. */
    private fun strongBoxAvailable(): Boolean =
        Build.VERSION.SDK_INT >= Build.VERSION_CODES.P &&
            context.packageManager.hasSystemFeature(STRONGBOX_FEATURE)

    private fun isStrongboxFallback(error: Exception): Boolean =
        error is StrongBoxUnavailableException || error is ProviderException

    private companion object {
        const val TAG = "KeystoreFlashCrypto"
        const val ANDROID_KEYSTORE = "AndroidKeyStore"
        const val STRONGBOX_FEATURE = "android.software.keystore.strongbox"
        const val CERT_SUBJECT = "CN=Flash Identity"
        const val CERT_BACKDATE_MS = 24L * 60 * 60 * 1000 // tolerate clock skew between peers
        const val CERT_VALIDITY_MS = 25L * 365 * 24 * 60 * 60 * 1000
        val X500_PRINCIPAL = X500Principal(CERT_SUBJECT)
    }
}
