package com.transfer.flash.core.security.group

import com.transfer.flash.core.security.crypto.constantTimeBytesEqual
import com.transfer.flash.core.security.crypto.secureRandomBytes

/**
 * Holder for a 32-byte group secret (ADR-073, protocol "Keys and commitment").
 *
 * Generated by the founder at group creation (or rotated by admins). Never user-typed,
 * never derived from passwords, and never serialized or logged in clear text.
 */
public class GroupSecret private constructor(
    private val bytes: ByteArray,
) {
    init {
        require(bytes.size == SECRET_SIZE_BYTES) {
            "GroupSecret must be exactly $SECRET_SIZE_BYTES bytes, was ${bytes.size}"
        }
    }

    /** Returns a defensive copy of the secret bytes. */
    public fun toByteArray(): ByteArray = bytes.copyOf()

    /**
     * Constant-time comparison between two [GroupSecret] instances.
     *
     * Prevents timing side channels when comparing secrets.
     */
    public fun constantTimeEquals(other: GroupSecret?): Boolean {
        if (other == null) return false
        return constantTimeBytesEqual(bytes, other.bytes)
    }

    /**
     * Overrides [equals] to use constant-time comparison, ensuring no early-out
     * timing leakage occurs when compared using `==`.
     */
    override fun equals(other: Any?): Boolean {
        if (this === other) return true
        if (other !is GroupSecret) return false
        return constantTimeEquals(other)
    }

    override fun hashCode(): Int = bytes.contentHashCode()

    /**
     * Redacted string representation. Never exposes secret bytes in logs, crashes, or debug output.
     */
    override fun toString(): String = "GroupSecret(redacted)"

    public companion object {
        public const val SECRET_SIZE_BYTES: Int = 32

        /** Generates a new cryptographically secure 32-byte group secret. */
        public fun generate(): GroupSecret = GroupSecret(secureRandomBytes(SECRET_SIZE_BYTES))

        /** Wraps existing 32 bytes into a [GroupSecret] after verifying its length. */
        public fun fromBytes(bytes: ByteArray): GroupSecret {
            require(bytes.size == SECRET_SIZE_BYTES) {
                "GroupSecret must be exactly $SECRET_SIZE_BYTES bytes, was ${bytes.size}"
            }
            return GroupSecret(bytes.copyOf())
        }
    }
}
